import { Topic } from '@/adapters/learning';

// ML Curriculum Topics (Comprehensive list)
export const topics: Topic[] = [
    // STATISTICS MODULE
    {
        id: 'descriptive-statistics',
        slug: 'descriptive-statistics',
        subjectSlug: 'foundations',
        moduleSlug: 'statistics',
        title: 'Descriptive Statistics Overview',
        description: 'Mean, median, mode and basic data summarization',
        order: 1,
        prerequisites: [],
        outcomes: ['Calculate central tendency', 'Understand data distributions'],
    },
    {
        id: 'population-vs-sample',
        slug: 'population-vs-sample',
        subjectSlug: 'foundations',
        moduleSlug: 'statistics',
        title: 'Population vs Sample',
        description: 'Why we sample and the law of large numbers',
        order: 2,
        prerequisites: ['descriptive-statistics'],
        outcomes: ['Distinguish population from sample', 'Understand sampling bias'],
    },
    {
        id: 'central-tendency',
        slug: 'central-tendency',
        subjectSlug: 'foundations',
        moduleSlug: 'statistics',
        title: 'Measures of Central Tendency',
        description: 'Balance points: Mean, Median, and Mode',
        order: 3,
        prerequisites: ['population-vs-sample'],
        outcomes: ['Calculate mean and median', 'Handle outliers'],
    },
    {
        id: 'dispersion-measures',
        slug: 'dispersion-measures',
        subjectSlug: 'foundations',
        moduleSlug: 'statistics',
        title: 'Measures of Dispersion',
        description: 'Variance, standard deviation, and range',
        order: 4,
        prerequisites: ['central-tendency'],
        outcomes: ['Calculate variance and std dev', 'Interpret data spread'],
    },
    {
        id: 'law-of-large-numbers',
        slug: 'law-of-large-numbers',
        subjectSlug: 'foundations',
        moduleSlug: 'statistics',
        title: 'Law of Large Numbers',
        description: 'Why more data leads to better estimates',
        order: 5,
        prerequisites: ['population-vs-sample'],
        outcomes: ['Understand convergence', 'Visualize LLN in action'],
    },

    // PROBABILITY MODULE
    {
        id: 'random-variables',
        slug: 'random-variables',
        subjectSlug: 'foundations',
        moduleSlug: 'probability',
        title: 'Random Variables & Probability Distributions',
        description: 'Introduction to discrete and continuous random variables',
        order: 1,
        prerequisites: [],
        outcomes: ['Identify random variables', 'Understand PMFs and PDFs'],
    },
    {
        id: 'probability-distributions',
        slug: 'probability-distributions',
        subjectSlug: 'foundations',
        moduleSlug: 'probability',
        title: 'Common Probability Distributions',
        description: 'Normal, Bernoulli, and Binomial distributions',
        order: 2,
        prerequisites: ['random-variables'],
        outcomes: ['Visualize distribution shapes', 'Understand mean and variance'],
    },
    {
        id: 'bayes-theorem',
        slug: 'bayes-theorem',
        subjectSlug: 'foundations',
        moduleSlug: 'probability',
        title: "Conditional Probability & Bayes' Theorem",
        description: 'Conditional probability and belief updating',
        order: 3,
        prerequisites: ['probability-distributions'],
        outcomes: ['Apply Bayes formula', 'Understand prior and posterior'],
    },
    {
        id: 'poisson-distribution',
        slug: 'poisson-distribution',
        subjectSlug: 'foundations',
        moduleSlug: 'probability',
        title: 'Poisson Distribution',
        description: 'Modeling counts of independent events',
        order: 4,
        prerequisites: ['probability-distributions'],
        outcomes: ['Understand λ parameter', 'Model rare events'],
    },
    {
        id: 'exponential-distribution',
        slug: 'exponential-distribution',
        subjectSlug: 'foundations',
        moduleSlug: 'probability',
        title: 'Exponential Distribution',
        description: 'Modeling time between events',
        order: 5,
        prerequisites: ['poisson-distribution'],
        outcomes: ['Understand memorylessness', 'Model waiting times'],
    },
    {
        id: 'uniform-distribution',
        slug: 'uniform-distribution',
        subjectSlug: 'foundations',
        moduleSlug: 'probability',
        title: 'Uniform Distribution',
        description: 'Equal probability across a range',
        order: 6,
        prerequisites: ['random-variables'],
        outcomes: ['Understand flat probability', 'Apply to initialization'],
    },

    // LINEAR ALGEBRA MODULE (Foundations)
    {
        id: 'vector-operations',
        slug: 'vector-operations',
        subjectSlug: 'foundations',
        moduleSlug: 'linear-algebra',
        title: 'Vector Operations (Addition, Dot Product, Norms)',
        description: 'Addition, dot product, and norms',
        order: 1,
        prerequisites: [],
        outcomes: ['Perform vector arithmetic', 'Calculate similarity'],
    },
    {
        id: 'matrix-transformations',
        slug: 'matrix-transformations',
        subjectSlug: 'foundations',
        moduleSlug: 'linear-algebra',
        title: 'Matrices & Matrix Multiplication',
        description: 'Matrix multiplication and linear mappings',
        order: 2,
        prerequisites: ['vector-operations'],
        outcomes: ['Understand matrix multiplication', 'Visualize space transformations'],
    },
    {
        id: 'matrix-properties',
        slug: 'matrix-properties',
        subjectSlug: 'foundations',
        moduleSlug: 'linear-algebra',
        title: 'Matrix Properties: Transpose, Inverse, Rank',
        description: 'Properties and operations that define matrix behavior',
        order: 3,
        prerequisites: ['matrix-transformations'],
        outcomes: ['Calculate inverse', 'Identify rank collapse'],
    },
    {
        id: 'linear-independence-basis',
        slug: 'linear-independence-basis',
        subjectSlug: 'foundations',
        moduleSlug: 'linear-algebra',
        title: 'Linear Independence & Basis',
        description: 'Defining the coordinate system of your data',
        order: 4,
        prerequisites: ['matrix-properties'],
        outcomes: ['Test for independence', 'Understand span and basis'],
    },
    {
        id: 'eigenvalues-eigenvectors',
        slug: 'eigenvalues-eigenvectors',
        subjectSlug: 'foundations',
        moduleSlug: 'linear-algebra',
        title: 'Eigenvalues & Eigenvectors',
        description: 'Identifying stable directions in transformations',
        order: 5,
        prerequisites: ['matrix-transformations'],
        outcomes: ['Calculate eigenvalues', 'Understand PCA foundations'],
    },
    {
        id: 'svd',
        slug: 'svd',
        subjectSlug: 'foundations',
        moduleSlug: 'linear-algebra',
        title: 'Singular Value Decomposition (SVD)',
        description: 'Decomposing matrices for data compression',
        order: 6,
        prerequisites: ['eigenvalues-eigenvectors'],
        outcomes: ['Understand SVD components', 'Apply low-rank approximation'],
    },

    // OPTIMIZATION MODULE (Foundations)
    {
        id: 'objective-function',
        slug: 'objective-function',
        subjectSlug: 'foundations',
        moduleSlug: 'optimization',
        title: 'The Objective Function',
        description: 'Defining and measuring model error',
        order: 1,
        prerequisites: [],
        outcomes: ['Understand loss functions', 'Interpret MSE and Cross-Entropy'],
    },
    {
        id: 'gradients-chain-rule',
        slug: 'gradients-chain-rule',
        subjectSlug: 'foundations',
        moduleSlug: 'optimization',
        title: 'Gradients and the Chain Rule',
        description: 'Finding the direction of steepest descent',
        order: 2,
        prerequisites: ['objective-function'],
        outcomes: ['Calculate partial derivatives', 'Understand chain rule'],
    },
    {
        id: 'gradient-descent',
        slug: 'gradient-descent',
        subjectSlug: 'foundations',
        moduleSlug: 'optimization',
        title: 'Gradient Descent Algorithms',
        description: 'Iterative optimization for model training',
        order: 3,
        prerequisites: ['gradients-chain-rule'],
        outcomes: ['Implement gradient descent', 'Tune learning rates'],
    },

    // PYTHON BASICS MODULE (Programming)
    {
        id: 'python-syntax',
        slug: 'python-syntax',
        subjectSlug: 'programming',
        moduleSlug: 'python-basics',
        title: 'Python Syntax for Data Science',
        description: 'Core syntax and variables for data science',
        order: 1,
        prerequisites: [],
        outcomes: ['Write valid Python code', 'Understand dynamic typing'],
    },
    {
        id: 'data-structures',
        slug: 'data-structures',
        subjectSlug: 'programming',
        moduleSlug: 'python-basics',
        title: 'Data Types and Data Structures',
        description: 'Lists, dictionaries, and mutability',
        order: 2,
        prerequisites: ['python-syntax'],
        outcomes: ['Use core collections', 'Manage memory references'],
    },
    {
        id: 'control-flow',
        slug: 'control-flow',
        subjectSlug: 'programming',
        moduleSlug: 'python-basics',
        title: 'Control Flow',
        description: 'Conditionals and loops for data processing',
        order: 3,
        prerequisites: ['data-structures'],
        outcomes: ['Write conditional logic', 'Iterate over datasets'],
    },
    {
        id: 'functions-modules',
        slug: 'functions-modules',
        subjectSlug: 'programming',
        moduleSlug: 'python-basics',
        title: 'Functions and Modules',
        description: 'Encapsulating logic for reproducibility',
        order: 4,
        prerequisites: ['control-flow'],
        outcomes: ['Write modular code', 'Manage namespaces'],
    },
    {
        id: 'error-handling',
        slug: 'error-handling',
        subjectSlug: 'programming',
        moduleSlug: 'python-basics',
        title: 'Error Handling',
        description: 'Failing safely and intentionally',
        order: 5,
        prerequisites: ['functions-modules'],
        outcomes: ['Handle exceptions', 'Validate data invariants'],
    },
    {
        id: 'clean-code',
        slug: 'clean-code',
        subjectSlug: 'programming',
        moduleSlug: 'python-basics',
        title: 'Writing Clean, Maintainable Code',
        description: 'Clarity beats cleverness',
        order: 6,
        prerequisites: ['error-handling'],
        outcomes: ['Apply PEP 8', 'Structure pipelines'],
    },

    // NUMPY MODULE (Programming)
    {
        id: 'numpy-arrays',
        slug: 'numpy-arrays',
        subjectSlug: 'programming',
        moduleSlug: 'numpy',
        title: 'NumPy Arrays',
        description: 'Fast numerical computation and memory layout',
        order: 1,
        prerequisites: ['python-basics'],
        outcomes: ['Create ndarrays', 'Understand vectorization'],
    },
    {
        id: 'broadcasting',
        slug: 'broadcasting',
        subjectSlug: 'programming',
        moduleSlug: 'numpy',
        title: 'Array Shapes and Broadcasting',
        description: 'Aligning arrays for mathematical operations',
        order: 2,
        prerequisites: ['numpy-arrays'],
        outcomes: ['Handle dimension mismatches', 'Apply broadcasting rules'],
    },
    {
        id: 'numerical-stability',
        slug: 'numerical-stability',
        subjectSlug: 'programming',
        moduleSlug: 'numpy',
        title: 'Numerical Stability',
        description: 'Managing floating-point precision issues',
        order: 3,
        prerequisites: ['broadcasting'],
        outcomes: ['Avoid overflow/underflow', 'Write stable math code'],
    },
    {
        id: 'fancy-indexing',
        slug: 'fancy-indexing',
        subjectSlug: 'programming',
        moduleSlug: 'numpy',
        title: 'Fancy Indexing',
        description: 'Advanced selection with arrays',
        order: 4,
        prerequisites: ['numpy-arrays'],
        outcomes: ['Select non-contiguous data', 'Understand slice copies'],
    },
    {
        id: 'boolean-indexing',
        slug: 'boolean-indexing',
        subjectSlug: 'programming',
        moduleSlug: 'numpy',
        title: 'Boolean Indexing & np.where',
        description: 'Filtering data with masks',
        order: 5,
        prerequisites: ['fancy-indexing'],
        outcomes: ['Apply conditional masks', 'Use vectorized if-else'],
    },
    {
        id: 'memory-layout',
        slug: 'memory-layout',
        subjectSlug: 'programming',
        moduleSlug: 'numpy',
        title: 'Memory Layout: C-order vs Fortran-order',
        description: 'Optimizing cache locality',
        order: 6,
        prerequisites: ['numpy-arrays'],
        outcomes: ['Understand strides', 'Optimize axis-wise operations'],
    },

    // PANDAS MODULE (Programming)
    {
        id: 'pandas-io',
        slug: 'pandas-io',
        subjectSlug: 'programming',
        moduleSlug: 'pandas',
        title: 'Reading & Writing Data',
        description: 'Ingesting data from various formats',
        order: 1,
        prerequisites: ['numpy'],
        outcomes: ['Read CSV/Parquet/SQL', 'Specify dtypes and schemas'],
    },
    {
        id: 'pandas-indexing',
        slug: 'pandas-indexing',
        subjectSlug: 'programming',
        moduleSlug: 'pandas',
        title: 'Indexing & Filtering',
        description: 'loc, iloc, and boolean masking',
        order: 2,
        prerequisites: ['pandas-io'],
        outcomes: ['Label-based selection', 'Positional selection'],
    },
    {
        id: 'pandas-groupby',
        slug: 'pandas-groupby',
        subjectSlug: 'programming',
        moduleSlug: 'pandas',
        title: 'GroupBy & Aggregation',
        description: 'Split-Apply-Combine pattern',
        order: 3,
        prerequisites: ['pandas-indexing'],
        outcomes: ['Summarize data groups', 'Apply custom aggregations'],
    },
    {
        id: 'pandas-merge',
        slug: 'pandas-merge',
        subjectSlug: 'programming',
        moduleSlug: 'pandas',
        title: 'Merging & Joining',
        description: 'Relational operations in Pandas',
        order: 4,
        prerequisites: ['pandas-io'],
        outcomes: ['Combine datasets', 'Understand join types'],
    },
    {
        id: 'pandas-missing',
        slug: 'pandas-missing',
        subjectSlug: 'programming',
        moduleSlug: 'pandas',
        title: 'Handling Missing Data',
        description: 'Detection and imputation',
        order: 5,
        prerequisites: ['pandas-io'],
        outcomes: ['Identify NaNs', 'Apply filling strategies'],
    },
    {
        id: 'pandas-timeseries',
        slug: 'pandas-timeseries',
        subjectSlug: 'programming',
        moduleSlug: 'pandas',
        title: 'Time Series Handling',
        description: 'Resampling and rolling windows',
        order: 6,
        prerequisites: ['pandas-indexing'],
        outcomes: ['Handle datetime index', 'Apply moving averages'],
    },

    // MACHINE LEARNING - REGRESSION
    {
        id: 'linear-regression',
        slug: 'linear-regression',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Linear Regression',
        description: 'Fitting lines to data',
        order: 1,
        prerequisites: [],
        outcomes: ['Understand OLS', 'Interpret coefficients'],
    },
    {
        id: 'polynomial-regression',
        slug: 'polynomial-regression',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Polynomial Regression',
        description: 'Handling non-linearity',
        order: 2,
        prerequisites: ['linear-regression'],
        outcomes: ['Increase model flexibility', 'Identify overfitting'],
    },
    {
        id: 'regularization',
        slug: 'regularization',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Regularization (Ridge & Lasso)',
        description: 'L1 and L2 penalties',
        order: 3,
        prerequisites: ['polynomial-regression'],
        outcomes: ['Control model complexity', 'Perform feature selection'],
    },
    {
        id: 'elastic-net',
        slug: 'elastic-net',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Elastic Net Regression',
        description: 'Balancing L1 and L2',
        order: 4,
        prerequisites: ['regularization'],
        outcomes: ['Handle correlated features'],
    },
    {
        id: 'decision-tree-regression',
        slug: 'decision-tree-regression',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Decision Tree Regression',
        description: 'Non-parametric rule-based regression',
        order: 5,
        prerequisites: [],
        outcomes: ['Understand tree splits', 'Identify variance issues'],
    },
    {
        id: 'random-forest-regression',
        slug: 'random-forest-regression',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Random Forest Regression',
        description: 'Bagging for stability',
        order: 6,
        prerequisites: ['decision-tree-regression'],
        outcomes: ['Reduce variance', 'Ensemble predictions'],
    },
    {
        id: 'gradient-boosting-regression',
        slug: 'gradient-boosting-regression',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Gradient Boosting Regression',
        description: 'Sequential error correction',
        order: 6,
        prerequisites: ['random-forest-regression'],
        outcomes: ['Understand boosting', 'Tune learning rate'],
    },
    {
        id: 'svr',
        slug: 'svr',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Support Vector Regression (SVR)',
        description: 'The epsilon-sensitive tube',
        order: 8,
        prerequisites: ['linear-regression'],
        outcomes: ['Understand support vectors', 'Apply kernel trick'],
    },
    {
        id: 'knn-regression',
        slug: 'knn-regression',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'K-Nearest Neighbors (KNN) Regression',
        description: 'Averaging the neighborhood',
        order: 9,
        prerequisites: [],
        outcomes: ['Understand distance metrics', 'Manage K parameter'],
    },
    {
        id: 'gpr',
        slug: 'gpr',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Gaussian Process Regression (GPR)',
        description: 'Probabilistic uncertainty',
        order: 10,
        prerequisites: ['svr'],
        outcomes: ['Quantify uncertainty', 'Select kernels'],
    },
    {
        id: 'regression-metrics',
        slug: 'regression-metrics',
        subjectSlug: 'machine-learning',
        moduleSlug: 'regression',
        title: 'Evaluation Metrics',
        description: 'MSE, RMSE, MAE, R²',
        order: 11,
        prerequisites: ['linear-regression'],
        outcomes: ['Calculate error', 'Interpret performance'],
    },

    // DATA CLEANING (Data Handling)
    {
        id: 'missing-data',
        slug: 'missing-data',
        subjectSlug: 'data-handling',
        moduleSlug: 'data-cleaning',
        title: 'Missing Data Strategies',
        description: 'Imputation and removal strategies',
        order: 1,
        prerequisites: ['pandas'],
        outcomes: ['Identify null values', 'Apply imputation techniques'],
    },
    {
        id: 'duplicate-data',
        slug: 'duplicate-data',
        subjectSlug: 'data-handling',
        moduleSlug: 'data-cleaning',
        title: 'Duplicate Data',
        description: 'Identifying repeating samples',
        order: 2,
        prerequisites: ['missing-data'],
        outcomes: ['Deduplicate records', 'Avoid metric inflation'],
    },
    {
        id: 'quality-viz',
        slug: 'quality-viz',
        subjectSlug: 'data-handling',
        moduleSlug: 'data-cleaning',
        title: 'Model Result Visualization for Data Quality',
        description: 'Diagnostics for cleaner data',
        order: 3,
        prerequisites: ['missing-data'],
        outcomes: ['Analyze residuals', 'Identify systematic errors'],
    },
    {
        id: 'outlier-detection',
        slug: 'outlier-detection',
        subjectSlug: 'data-handling',
        moduleSlug: 'data-cleaning',
        title: 'Outlier Detection (IQR & Z-score)',
        description: 'Fencing the distribution',
        order: 4,
        prerequisites: ['missing-data'],
        outcomes: ['Identify anomalies', 'Understand robustness'],
    },
    {
        id: 'data-validation',
        slug: 'data-validation',
        subjectSlug: 'data-handling',
        moduleSlug: 'data-cleaning',
        title: 'Data Validation',
        description: 'Schema and constraint checks',
        order: 5,
        prerequisites: ['outlier-detection'],
        outcomes: ['Enforce data integrity', 'Build robust pipelines'],
    },

    // CLUSTERING MODULE (Machine Learning)
    {
        id: 'k-means',
        slug: 'k-means',
        subjectSlug: 'machine-learning',
        moduleSlug: 'clustering',
        title: 'K-Means Clustering',
        description: 'Grouping similar data points',
        order: 1,
        prerequisites: [],
        outcomes: ['Understand centroid optimization', 'Select optimal K via elbow method'],
    },

    // MODEL EVALUATION (Metrics)
    {
        id: 'why-eval',
        slug: 'why-eval',
        subjectSlug: 'model-evaluation',
        moduleSlug: 'metrics',
        title: 'Why Evaluation Matters',
        description: 'Accuracy is not enough',
        order: 1,
        prerequisites: [],
        outcomes: ['Differentiate training vs testing', 'Understand generalization'],
    },
    {
        id: 'regression-metrics-eval',
        slug: 'regression-metrics-eval',
        subjectSlug: 'model-evaluation',
        moduleSlug: 'metrics',
        title: 'Regression Metrics',
        description: 'RMSE, MAE, MAPE',
        order: 2,
        prerequisites: ['why-eval'],
        outcomes: ['Measure continuous error'],
    },
    {
        id: 'classification-metrics-eval',
        slug: 'classification-metrics-eval',
        subjectSlug: 'model-evaluation',
        moduleSlug: 'metrics',
        title: 'Classification Metrics',
        description: 'Precision, Recall, F1',
        order: 3,
        prerequisites: ['why-eval'],
        outcomes: ['Handle class imbalance'],
    },
    {
        id: 'conf-matrix',
        slug: 'conf-matrix',
        subjectSlug: 'model-evaluation',
        moduleSlug: 'metrics',
        title: 'Confusion Matrix',
        description: 'Decoding prediction errors',
        order: 4,
        prerequisites: ['classification-metrics-eval'],
        outcomes: ['Visualize TN, FP, FN, TP'],
    },
    {
        id: 'roc-auc',
        slug: 'roc-auc',
        subjectSlug: 'model-evaluation',
        moduleSlug: 'metrics',
        title: 'ROC and AUC',
        description: 'Evaluating thresholds',
        order: 5,
        prerequisites: ['conf-matrix'],
        outcomes: ['Calculate AUC', 'Compare classifiers'],
    },
    {
        id: 'pr-curves',
        slug: 'pr-curves',
        subjectSlug: 'model-evaluation',
        moduleSlug: 'metrics',
        title: 'Precision-Recall Curves',
        description: 'Imbalanced data performance',
        order: 6,
        prerequisites: ['roc-auc'],
        outcomes: ['Focus on minority class'],
    },
    {
        id: 'multiclass-metrics',
        slug: 'multiclass-metrics',
        subjectSlug: 'model-evaluation',
        moduleSlug: 'metrics',
        title: 'Multi-class Classification Metrics',
        description: 'Macro vs Micro averaging',
        order: 6,
        prerequisites: ['classification-metrics-eval'],
        outcomes: ['Average across classes'],
    },
    {
        id: 'brier-score',
        slug: 'brier-score',
        subjectSlug: 'model-evaluation',
        moduleSlug: 'metrics',
        title: 'Brier Score and Probability Scoring',
        description: 'Calibrating confidence',
        order: 8,
        prerequisites: ['roc-auc'],
        outcomes: ['Score probability predictions'],
    },

    // DEEP LEARNING SUBJECT
    {
        id: 'nn-architecture',
        slug: 'nn-architecture',
        subjectSlug: 'deep-learning',
        moduleSlug: 'neural-networks',
        title: 'Neural Network Architecture',
        description: 'Layers, neurons, and connectivity',
        order: 1,
        prerequisites: ['linear-algebra', 'optimization'],
        outcomes: ['Design network topology', 'Calculate parameter counts'],
    },
    {
        id: 'activation-functions',
        slug: 'activation-functions',
        subjectSlug: 'deep-learning',
        moduleSlug: 'neural-networks',
        title: 'Activation Functions',
        description: 'Introducing non-linearity (ReLU, Sigmoid, Tanh)',
        order: 2,
        prerequisites: ['nn-architecture'],
        outcomes: ['Select appropriate activations', 'Understand vanishing gradients'],
    },
    {
        id: 'backprop',
        slug: 'backprop',
        subjectSlug: 'deep-learning',
        moduleSlug: 'neural-networks',
        title: 'Forward and Backward Propagation',
        description: 'The engine of neural network learning',
        order: 3,
        prerequisites: ['activation-functions'],
        outcomes: ['Understand chain rule in NNs', 'Trace gradient flow'],
    },
    {
        id: 'convolution-op',
        slug: 'convolution-op',
        subjectSlug: 'deep-learning',
        moduleSlug: 'computer-vision',
        title: 'Convolution Operation',
        description: 'Spatial pattern recognition',
        order: 1,
        prerequisites: ['nn-architecture'],
        outcomes: ['Understand filters and kernels', 'Visualize feature maps'],
    },
    {
        id: 'rnn-basics',
        slug: 'rnn-basics',
        subjectSlug: 'deep-learning',
        moduleSlug: 'nlp',
        title: 'Recurrent Neural Networks (RNNs)',
        description: 'Processing sequential data with memory',
        order: 1,
        prerequisites: ['nn-architecture'],
        outcomes: ['Understand hidden states', 'Model temporal dependencies'],
    },
    {
        id: 'lstm-gru',
        slug: 'lstm-gru',
        subjectSlug: 'deep-learning',
        moduleSlug: 'nlp',
        title: 'LSTMs & GRUs (Gated Memory)',
        description: 'Solving long-term dependency issues',
        order: 2,
        prerequisites: ['rnn-basics'],
        outcomes: ['Understand gating mechanisms', 'Handle vanishing gradients in sequences'],
    },
    {
        id: 'attention-mech',
        slug: 'attention-mech',
        subjectSlug: 'deep-learning',
        moduleSlug: 'nlp',
        title: 'Attention Mechanism (Self-Attention)',
        description: 'Dynamic focus on sequence parts',
        order: 3,
        prerequisites: ['lstm-gru'],
        outcomes: ['Calculate query-key-value scores', 'Understand global context'],
    },
    {
        id: 'transformer',
        slug: 'transformer',
        subjectSlug: 'deep-learning',
        moduleSlug: 'nlp',
        title: 'The Transformer Architecture',
        description: 'Parallelized attention and positional encoding',
        order: 4,
        prerequisites: ['attention-mech'],
        outcomes: ['Understand encoder-decoder stacks', 'Scale DL models'],
    },
    {
        id: 'dropout-reg',
        slug: 'dropout-reg',
        subjectSlug: 'deep-learning',
        moduleSlug: 'optimization',
        title: 'Dropout Regularization',
        description: 'Preventing co-adaptation in deep networks',
        order: 1,
        prerequisites: ['nn-architecture'],
        outcomes: ['Apply dropout during training', 'Understand ensemble effect'],
    },
    {
        id: 'batch-norm',
        slug: 'batch-norm',
        subjectSlug: 'deep-learning',
        moduleSlug: 'optimization',
        title: 'Batch Normalization',
        description: 'Stabilizing internal covariate shift',
        order: 2,
        prerequisites: ['dropout-reg'],
        outcomes: ['Accelerate training', 'Apply normalization layers'],
    },
    {
        id: 'transfer-learning',
        slug: 'transfer-learning',
        subjectSlug: 'deep-learning',
        moduleSlug: 'applications',
        title: 'Transfer Learning',
        description: 'Leveraging pretrained knowledge',
        order: 1,
        prerequisites: ['nn-architecture'],
        outcomes: ['Fine-tune foundation models', 'Adapt to new domains'],
    },

    // ADVANCED ML & APPLICATIONS
    {
        id: 'nlp-pipeline',
        slug: 'nlp-pipeline',
        subjectSlug: 'advanced-ml',
        moduleSlug: 'nlp-advanced',
        title: 'Text Preprocessing & Tokenization',
        description: 'Turning raw text into numeric tensors',
        order: 1,
        prerequisites: ['programming'],
        outcomes: ['Implement BPE/WordPiece', 'Clean textual data'],
    },
    {
        id: 'word-embeddings',
        slug: 'word-embeddings',
        subjectSlug: 'advanced-ml',
        moduleSlug: 'nlp-advanced',
        title: 'Word Embeddings (Word2Vec & GloVe)',
        description: 'Semantic vector spaces',
        order: 2,
        prerequisites: ['nlp-pipeline'],
        outcomes: ['Apply pretrained vectors', 'Understand cosine similarity'],
    },
    {
        id: 'timeseries-decomp',
        slug: 'timeseries-decomp',
        subjectSlug: 'advanced-ml',
        moduleSlug: 'specialized',
        title: 'Time Series Decomposition',
        description: 'Trend, seasonality, and residuals',
        order: 1,
        prerequisites: ['statistics', 'pandas'],
        outcomes: ['Decompose signals', 'Identify seasonal patterns'],
    },
    {
        id: 'anomaly-detect',
        slug: 'anomaly-detect',
        subjectSlug: 'advanced-ml',
        moduleSlug: 'specialized',
        title: 'Statistically Outlier Detection',
        description: 'Identifying rare events/anomalies',
        order: 2,
        prerequisites: ['statistics'],
        outcomes: ['Implement isolation forests', 'Handle fraud/risk detection'],
    },
    {
        id: 'recommender-systems',
        slug: 'recommender-systems',
        subjectSlug: 'advanced-ml',
        moduleSlug: 'specialized',
        title: 'Recommender Systems',
        description: 'Collaborative vs content-based filtering',
        order: 3,
        prerequisites: ['machine-learning'],
        outcomes: ['Build matrix factorization models', 'Solve cold-start problems'],
    },

    // MLOPS SUBJECT
    {
        id: 'mlops-etl',
        slug: 'mlops-etl',
        subjectSlug: 'mlops',
        moduleSlug: 'production',
        title: 'Data Pipelines & ETL',
        description: 'Automating the data flow',
        order: 1,
        prerequisites: ['programming', 'pandas'],
        outcomes: ['Build repeatable pipelines', 'Ensure data lineage'],
    },
    {
        id: 'mlops-versioning',
        slug: 'mlops-versioning',
        subjectSlug: 'mlops',
        moduleSlug: 'production',
        title: 'Model Training & Versioning',
        description: 'Reproducible experiments',
        order: 2,
        prerequisites: ['mlops-etl'],
        outcomes: ['Use MLflow/DVC', 'Track model artifacts'],
    },
    {
        id: 'mlops-monitoring',
        slug: 'mlops-monitoring',
        subjectSlug: 'mlops',
        moduleSlug: 'production',
        title: 'Monitoring & Concept Drift',
        description: 'Detecting performance decay',
        order: 3,
        prerequisites: ['mlops-versioning'],
        outcomes: ['Identify drift', 'Automate retraining triggers'],
    },

    // ETHICS SUBJECT
    {
        id: 'ai-ethics',
        slug: 'ai-ethics',
        subjectSlug: 'ethics',
        moduleSlug: 'governance',
        title: 'AI Ethics & Fairness',
        description: 'Mitigating bias and ensuring equity',
        order: 1,
        prerequisites: ['machine-learning'],
        outcomes: ['Audit model bias', 'Implement fairness constraints'],
    },
];

// Helper functions
export function getTopicsByModule(moduleSlug: string, subjectSlug?: string): Topic[] {
    return topics
        .filter(t => t.moduleSlug === moduleSlug && (!subjectSlug || t.subjectSlug === subjectSlug))
        .sort((a, b) => a.order - b.order);
}

export function getTopicBySlug(slug: string): Topic | undefined {
    return topics.find(t => t.slug === slug);
}
